services:
  suwayomi:
    image: ghcr.io/suwayomi/suwayomi-server:stable
    container_name: suwayomi
    restart: unless-stopped

    ports:
      - "4567:4567"

    environment:
      TZ: Asia/Kolkata

      # Server
      BIND_IP: 0.0.0.0
      BIND_PORT: 4567

      # Headless/Docker
      WEB_UI_ENABLED: "true"

      # Download settings
      DOWNLOAD_AS_CBZ: "true"

      # Extension store
      EXTENSION_STORES: >-
        ["https://github.com/keiyoushi/extensions/raw/repo/index.pb"]

      # Byparr / Cloudflare bypass
      FLARESOLVERR_ENABLED: "true"
      FLARESOLVERR_URL: "http://byparr:8191"
    depends_on:
      - byparr

  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    restart: unless-stopped

    environment:
      TZ: Asia/Kolkata

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      TZ: Asia/Kolkata 